anotacao/urls.py
from django.urls import path
from anotacao import views
from django.conf import settings
from django.conf.urls.static import static
# URLS centaris do app

urlpatterns = [
    path('login/', views.login_view, name='login'), # Rota de login
    path('logout/', views.logout_view, name='logout'), # Rota de logout
    path('', views.home_view, name='home'), # Rota da home inicial
    path('alterar-senha/', views.alterar_senha_view, name='alterar_senha'), # Rota para alterar senha
    path('anotacoes/', views.cadete_anotacoes_view, name='cadete_anotacoes'), # Rota das anotações pessoais dos cadetes
    path('cadetes/', views.lista_cadetes_view, name='lista_cadetes'), # Rota da relação de cadetes para anotar
    path('criar-anotacao_ajax/', views.criar_anotacao_ajax_view, name='criar_anotacao_ajax'), # Rota para criação de anotações
    path('comandante-anotacoes/', views.comandante_anotacoes_view, name='comandante_anotacoes'),  # Rota para o oficial comandante
    path('comandante-anotacoes/despachar_ajax/<int:anotacao_id>/', views.despachar_anotacao_ajax_view, name='despachar_anotacao_ajax'),  # Rota para despachar anotações
    path('comandante-anotacoes/anotacoes/excluir/<int:anotacao_id>/', views.excluir_anotacao_view, name='excluir_anotacao'),
    path('anotacoes-despachadas', views.anotacoes_despachadas_view, name='anotacoes_despachadas'),  # Rota para despachar anotações
    path('historico_exportacoes/', views.historico_exportacoes_view, name='historico_exportacoes'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("anotacao.urls"))
]

anotacao/models.py
from django.db import models

class TurmaCadetes(models.Model):
    turma = models.CharField(max_length=20, unique=True)
    
    def __str__(self) -> str:
        return self.turma

class UserMilitar(models.Model):
    TIPOS_CARGO = [
        ("Oficial_comandante", "Oficial Comandante"),
        ("Oficial", "Oficial"),
        ("Cadete", "Cadete"),
    ]
    
    nome = models.CharField(max_length=50)
    numerica = models.CharField(max_length=20, null=True, blank=True)
    cargo = models.CharField(max_length=20, choices=TIPOS_CARGO)
    turma = models.ForeignKey(TurmaCadetes, null=True, blank=True, on_delete=models.SET_NULL)
    permissao_anotar = models.BooleanField(default=False)
    senha = models.CharField(max_length=255)
    cadete_de_dia = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f"{self.nome} ({self.numerica})"
    
class Anotacao(models.Model):
    TIPOS_ANOTACAO = [
        ("positiva", "Positiva"),
        ("negativa", "Negativa"),
    ]
    TIPOS_DESPACHO = [
        ("pernoite", "Pernoite"),
        ("revista", "Revista"),
        ("outros", "Outros")
    ]
    tipo_anotacao = models.CharField(max_length=10, choices=TIPOS_ANOTACAO)
    motivo = models.TextField()
    cadete_anotado = models.ForeignKey(UserMilitar, on_delete=models.CASCADE) 
    criado_por = models.ForeignKey(UserMilitar, on_delete=models.SET_NULL, null=True, related_name='criado_por')
    status = models.CharField(max_length=20, default='notificada')
    criada_em = models.DateTimeField(auto_now_add=True) 
    despacho = models.CharField(max_length=10, choices=TIPOS_DESPACHO, null=True, blank=True)
    despachado_por = models.ForeignKey(UserMilitar, on_delete=models.SET_NULL, null=True, blank=True, related_name='despachado_por')
    data_cumprimento = models.DateField(null=True, blank=True)

class ArquivoExportado(models.Model):
    nome_arquivo = models.CharField(max_length=255)
    data_exportacao = models.DateTimeField(auto_now_add=True)
    arquivo = models.FileField(upload_to='exportacoes/')
    exportado_por = models.ForeignKey(UserMilitar, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome_arquivo

anotacao/forms.py
from django import forms
from anotacao.models import Anotacao

class LoginForm(forms.Form):
    nome_ou_numerica = forms.CharField(max_length=100, label='Nome ou Numérica')
    senha = forms.CharField(widget=forms.PasswordInput, label='Senha')

from django import forms
from .models import UserMilitar

class AlterarSenhaForm(forms.Form):
    nova_senha = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Digite sua nova senha'}),
        label="Nova Senha",
        max_length=255,
        required=True
    )
    confirmar_senha = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirme sua nova senha'}),
        label="Confirmar Senha",
        max_length=255,
        required=True
    )

    def __init__(self, *args, **kwargs):
        self.usuario = kwargs.pop('usuario', None)
        super().__init__(*args, **kwargs)

    # Validação do formulário como um todo
    def clean(self):
        cleaned_data = super().clean()
        nova_senha = cleaned_data.get("nova_senha")
        confirmar_senha = cleaned_data.get("confirmar_senha")

        # Verificar se as senhas coincidem
        if nova_senha and confirmar_senha:
            if nova_senha != confirmar_senha:
                raise forms.ValidationError("As senhas não coincidem.")
        
        # Verificar se a nova senha é a mesma que a antiga
        if self.usuario and nova_senha and self.usuario.senha == nova_senha:
            raise forms.ValidationError("A nova senha não pode ser a mesma que a senha antiga.")

        return cleaned_data

class AnotacaoForm(forms.ModelForm):
    class Meta:
        model = Anotacao
        fields = ['tipo_anotacao', 'motivo']
        labels = {
            'tipo_anotacao': 'Tipo de Anotação',
            'motivo': 'Motivo'
        }
        widgets = {
            'tipo_anotacao': forms.Select(
                choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')],
                attrs={'class': 'form-control'}  # Adiciona a classe form-control
            ),
            'motivo': forms.Textarea(attrs={'class': 'form-control','rows': 4}),
        }

anotacao/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.hashers import make_password, check_password
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.files.base import ContentFile
import io

import pandas as pd
import openpyxl

from anotacao.models import UserMilitar, Anotacao, TurmaCadetes, ArquivoExportado
from anotacao.forms import LoginForm, AlterarSenhaForm,AnotacaoForm
from anotacao.decorators import usuario_autenticado

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            nome_ou_numerica = form.cleaned_data['nome_ou_numerica']
            senha = form.cleaned_data['senha']

            usuario = UserMilitar.objects.filter(
                Q(nome=nome_ou_numerica) | Q(numerica=nome_ou_numerica)
            ).first()

            if usuario: 
                if senha == usuario.senha or check_password(senha, usuario.senha):
                    request.session['user_id'] = usuario.id
                    return redirect('home')
                else:
                    messages.error(request, 'Senha Incorreta')
            else:
                messages.error(request, 'Usuário não encontrado')

    else:
        form = LoginForm()

    return render(request, 'anotacao/login.html', {'form': form})

def logout_view(request):
    request.session.flush()
    return redirect('login')

@usuario_autenticado
def alterar_senha_view(request):
    usuario = request.usuario

    if request.method == 'POST':
        form = AlterarSenhaForm(request.POST, usuario=usuario)
        if form.is_valid():
            # Se o formulário for válido, atualize a senha do usuário
            nova_senha = form.cleaned_data['nova_senha']
            usuario.senha = make_password(nova_senha)  # Aplica a hash da nova senha
            usuario.save()
            messages.success(request, "Sua senha foi alterada com sucesso!")  # Mensagem de sucesso
            return redirect('home')  # Redireciona para a página inicial
        else:
            # Se o formulário for inválido, exibe os erros
            messages.error(request, "Houve um erro ao alterar sua senha. Verifique os campos abaixo.")
    else:
        form = AlterarSenhaForm(usuario=usuario)

    return render(request, 'anotacao/alterar_senha.html', {
        'usuario': usuario,
        'form': form,
    })

@usuario_autenticado
def home_view(request):
    usuario = request.usuario
    
    return render(request, 'anotacao/home.html', {
        'usuario': usuario,
    })

@usuario_autenticado
def cadete_anotacoes_view(request):
    if request.usuario.cargo != 'Cadete':
        return redirect('home')

    cadete_anotado = request.usuario
    anotacoes_notificadas = Anotacao.objects.filter(cadete_anotado=cadete_anotado, status='notificada')
    anotacoes_despachadas = Anotacao.objects.filter(cadete_anotado=cadete_anotado, status='despachada')

    return render(request, 'anotacao/cadete_anotacoes.html', {
        'usuario': cadete_anotado,
        'anotacoes_notificadas': anotacoes_notificadas,
        'anotacoes_despachadas': anotacoes_despachadas,
    })

@usuario_autenticado
def lista_cadetes_view(request):
    usuario = request.usuario  

    if usuario.cargo not in ['Oficial', 'Oficial_comandante'] and not usuario.permissao_anotar:
        return redirect('home')
    
    turmas = TurmaCadetes.objects.all()
    turma_selecionada = request.GET.get('turma')
    if turma_selecionada:
        cadetes = UserMilitar.objects.filter(cargo='Cadete', turma__id=turma_selecionada).order_by('numerica')
    else:
        cadetes = UserMilitar.objects.filter(cargo='Cadete')

    return render(request, 'anotacao/relacao_cadetes.html', {
        'usuario': usuario,
        'cadetes': cadetes,
        'turmas': turmas,
        'turma_selecionada': turma_selecionada
    })

@usuario_autenticado
def criar_anotacao_ajax_view(request):
    cadete_id = request.GET.get('cadete_id')
    cadete_anotado = get_object_or_404(UserMilitar, id=cadete_id, cargo='Cadete')
    
    usuario = request.usuario  
    if usuario.cargo not in ['Oficial', 'Oficial_comandante'] and not usuario.permissao_anotar:
        return redirect('home')
    
    if request.method == 'POST':
        form = AnotacaoForm(request.POST)
        if form.is_valid():
            anotacao = form.save(commit=False)
            anotacao.cadete_anotado = cadete_anotado 
            anotacao.criado_por = request.usuario  
            anotacao.status = 'notificada'  
            anotacao.criada_em = timezone.now()  
            anotacao.save()
            return JsonResponse({'success': True})  # Retorno de sucesso
    else:
        form = AnotacaoForm()

    # Renderiza o formulário como string HTML e envia via JsonResponse
    html_form = render_to_string('anotacao/criar_anotacao_ajax.html', {'form': form, 'cadete_anotado': cadete_anotado, 'usuario': usuario}, request=request)
    return JsonResponse({'html_form': html_form})

@usuario_autenticado
def comandante_anotacoes_view(request):
    usuario = request.usuario
    if usuario.cargo != 'Oficial_comandante':
        return redirect('home')

    turma_selecionada = request.GET.get('turma', '')

    # Filtrar cadetes pela turma e ordenar por 'numerica'
    cadetes = UserMilitar.objects.filter(cargo='Cadete')
    if turma_selecionada:
        cadetes = cadetes.filter(turma_id=turma_selecionada)
    cadetes = cadetes.order_by('numerica')  # Ordena cadetes pela numérica

    # Coletar as anotações para os cadetes, somente as que não foram despachadas
    anotacoes = []
    for cadete in cadetes:
        anotacoes_cadete = Anotacao.objects.filter(
            cadete_anotado=cadete, status='notificada'
        ).order_by('-tipo_anotacao', 'criada_em')  # Ordena por tipo (positivo primeiro) e data
        anotacoes.extend(anotacoes_cadete)

    turmas = TurmaCadetes.objects.all()

    context = {
        'usuario': usuario,
        'anotacoes': anotacoes,
        'turmas': turmas,
        'turma_selecionada': turma_selecionada,
    }
    return render(request, 'anotacao/comandante_anotacoes.html', context)

@usuario_autenticado
def excluir_anotacao_view(request, anotacao_id):
    if request.method == 'POST':
        anotacao = get_object_or_404(Anotacao, id=anotacao_id)
        anotacao.delete()  # Excluir a anotação
        return JsonResponse({'success': True})  # Retorna sucesso

    return JsonResponse({'success': False})  # Se não for um método DELETE ou algo der errado


@usuario_autenticado
def despachar_anotacao_ajax_view(request, anotacao_id):
    if request.usuario.cargo != 'Oficial_comandante':
        return redirect('home')

    anotacao = get_object_or_404(Anotacao, id=anotacao_id)

    if request.method == 'POST':
        if anotacao.tipo_anotacao == 'negativa':
            despacho = request.POST.get('despacho')
            data_cumprimento = request.POST.get('data_cumprimento')
            
            # Salvar a anotação se o despacho for válido
            if despacho in ['pernoite', 'revista', 'outros'] and data_cumprimento:
                if despacho == 'outros':
                    despacho = request.POST.get('outroDespacho')
                    
                anotacao.status = 'despachada'
                anotacao.despacho = despacho
                anotacao.data_cumprimento = data_cumprimento
                anotacao.despachado_por = request.usuario
                anotacao.save()  # Salva a anotação no banco
                return JsonResponse({'success': True})  # Retorna sucesso


        elif anotacao.tipo_anotacao == 'positiva':
            anotacao_negativa_id = request.POST.get('anotacao_negativa_id')
            if anotacao_negativa_id:
                try:
                    anotacao_negativa = Anotacao.objects.get(
                        id=anotacao_negativa_id,
                        cadete_anotado=anotacao.cadete_anotado,
                        tipo_anotacao='negativa',
                        status='notificada'
                    )
                    anotacao_negativa.delete()
                except Anotacao.DoesNotExist:
                    pass
            anotacao.delete()
            return JsonResponse({'success': True})  # Sucesso

    # Carregar as anotações negativas apenas se a anotação for positiva
    anotacoes_negativas = []
    if anotacao.tipo_anotacao == 'positiva':
        anotacoes_negativas = Anotacao.objects.filter(
            cadete_anotado=anotacao.cadete_anotado,
            tipo_anotacao='negativa',
            status='notificada'
        )

    # Renderizar o modal em formato JSON
    html_form = render_to_string(
        'anotacao/despachar_anotacao_ajax.html',
        {'anotacao': anotacao, 'anotacoes_negativas': anotacoes_negativas},
        request=request
    )
    return JsonResponse({'html_form': html_form})


@usuario_autenticado
def anotacoes_despachadas_view(request):
    usuario = request.usuario
    if usuario.cargo != 'Oficial_comandante':
        return redirect('home')

    # Obter anotações despachadas
    anotacoes_despachadas = Anotacao.objects.filter(status='despachada').order_by('cadete_anotado__turma', 'cadete_anotado__numerica')

    # Se o comandante submeter o formulário para exportar
    if request.method == 'POST':
        nome_arquivo = request.POST.get('nome_arquivo')
        if not nome_arquivo:
            nome_arquivo = "anotacoes_despachadas"

        # Preparar os dados para exportação
        dados = []
        for anotacao in anotacoes_despachadas:
            dados.append({
                'Turma': anotacao.cadete_anotado.turma.turma,
                'Cadete': f"{anotacao.cadete_anotado.numerica} - {anotacao.cadete_anotado.nome}",

anotacao/templates/anotacao/alterar_senha.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAPPA - Alterar Senha</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'anotacao/img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'anotacao/css/user_login.css' %}">
</head>
<body>
    <div class="form-container">
        <h2>Alterar Senha</h2>

        <!-- Exibe mensagens de erro ou sucesso -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{% if message.tags %}{{ message.tags }}{% endif %}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            
            <!-- Exibe os erros não relacionados a um campo específico -->
            {% if form.non_field_errors %}
                <ul class="errorlist">
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            
            <!-- Nova senha -->
            <label for="nova_senha">Nova Senha</label>
            <div class="input-container">
                {{ form.nova_senha }}
                <i class="fas fa-eye" id="togglePasswordNova"></i>
            </div>
        
            <!-- Confirmar senha -->
            <label for="confirmar_senha">Confirmar Senha</label>
            <div class="input-container">
                {{ form.confirmar_senha }}
                <i class="fas fa-eye" id="togglePasswordConfirma"></i>
            </div>
        
            <!-- Botões de ação -->
            <div class="button-container">
                <button type="submit">Salvar</button>
                <a href="{% url 'home' %}" class="btn-cancel">Cancelar</a>
            </div>

    <script>
        // Toggle visibility for nova senha
        const togglePasswordNova = document.querySelector('#togglePasswordNova');
        const novaSenha = document.querySelector('#id_nova_senha');

        togglePasswordNova.addEventListener('click', function () {
            const type = novaSenha.getAttribute('type') === 'password' ? 'text' : 'password';
            novaSenha.setAttribute('type', type);
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });

        // Toggle visibility for confirmar senha
        const togglePasswordConfirma = document.querySelector('#togglePasswordConfirma');
        const confirmarSenha = document.querySelector('#id_confirmar_senha');

        togglePasswordConfirma.addEventListener('click', function () {
            const type = confirmarSenha.getAttribute('type') === 'password' ? 'text' : 'password';
            confirmarSenha.setAttribute('type', type);
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    </script>
</body>
</html>

anotacao/templates/anotacao/anotacoes_despachadas.html
{% extends "anotacao/home.html" %}

{% block title %}{{ block.super }}Anotações Despachadas{% endblock title %}
{% block includes %}
    {{ block.super }}
    <script>
        function confirmarExportacao() {
            // Confirmação antes de exportar
            return confirm('Tem certeza de que deseja exportar as anotações despachadas para um arquivo Excel?');
        }
    </script>
{% endblock includes %}

{% block link_style %}
    {% load static %}
    <link rel="stylesheet" href="{% static "anotacao/css/arquivo.css" %}">
{% endblock link_style %}

{% block nav_bar %}
    {{ block.super }}
{% endblock nav_bar %}

{% block main_content %}
    <div class="arquivo-anotacoes-container">

        <h2 class="titulo-principal">Exportar Anotações Despachadas</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if anotacoes_despachadas %}
            <form method="post" id="exportarForm" onsubmit="return confirmarExportacao();">
                {% csrf_token %}
                <div class="form-group">
                    <label for="nome_arquivo">Nome do Arquivo:</label>
                    <input type="text" id="nome_arquivo" name="nome_arquivo" placeholder="Digite o nome do arquivo" required>
                </div>

                <button type="submit" class="btn-exportar">Exportar para Excel</button>
            </form>
        {% endif %}

        <h3 class="sub-titulo">Vizualização do arquivo</h3>
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Turma</th>
                        <th>Cadete</th>
                        <th>Motivo</th>
                        <th>Tipo Despacho</th>
                        <th>Ass. Ciência</th>
                        <th>Data Cumprimento</th>
                        <th>Ass. Cumprimento</th>
                    </tr>
                </thead>
                <tbody>
                    {% for anotacao in anotacoes_despachadas %}
                    <tr>
                        <td>{{ anotacao.cadete_anotado.turma.turma }}</td>
                        <td>{{ anotacao.cadete_anotado.numerica }} - {{ anotacao.cadete_anotado.nome }}</td>
                        <td>
                            Anotado Negativamente por {{ anotacao.criado_por.cargo }} {{ anotacao.criado_por.nome }} em {{ anotacao.criada_em|date:"d/m/Y H:i" }}. Motivo: {{ anotacao.motivo }}
                        </td>
                        <td>{{ anotacao.despacho }} - {{ anotacao.data_cumprimento|date:"d/m/Y" }}</td>
                        <td></td>
                        <td>__/__/____</td>
                        <td></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7">Nenhuma anotação despachada encontrada.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>
{% endblock main_content %}

anotacao/templates/anotacao/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@900&family=Open+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'anotacao/img/favicon.ico' %}" type="image/x-icon">
    {% block includes %}{% endblock includes %}
    {% block link_style %}{% endblock link_style %}
    <script>
        function toggleMenu() {
            var nav = document.getElementById("nav-links");
            nav.classList.toggle("show"); // Alterna entre mostrar/esconder o menu
        }
    </script>
    
</head>
<body>
    <aside class="menu">
        <header class="nav-content menu-content">
            <button class="menu-toggle" onclick="toggleMenu()">&#9776;</button>
            <h1>
                <a href="{% url 'home' %}">
                    MAPPA
                </a>
            </h1>
            <nav>
                <ul id="nav-links" class="nav-links">
                    {% block nav_bar %}{% endblock nav_bar %}
                </ul>
            </nav>
        </header>
    </aside>
    <section>
        <div class='main-content'>
            {% block main_content %}{% endblock main_content %}
        </div>
    </section>
    

anotacao/templates/anotacao/criar_anotacao_ajax.html
<div class="modal-header">
    <h2>Anotar {{ cadete_anotado.nome }}</h2>
</div>

<div class="modal-body">
    <form method="post" id="anotacaoForm">
        {% csrf_token %}
        {{ form.as_p }} <!-- Exibe o formulário de forma padronizada (com campos e labels) -->

        <button type="submit" class="btn-submit">Salvar Anotação</button>
    </form>
</div>

<script>
    // Função para atualizar o placeholder dinamicamente
    function atualizarObservacao() {
        const tipoAnotacao = document.getElementById('id_tipo_anotacao').value;  // Campo do tipo de anotação
        const motivo = document.getElementById('id_motivo');  // Campo de motivo

        // Define o placeholder padrão
        let placeholderTexto = "Escreva somente o motivo";

        // Verifica se o cargo do usuário e a permissão são adequados
        {% if usuario.cargo == 'Cadete' and usuario.permissao_anotar %}
            if (tipoAnotacao === 'positiva') {
                placeholderTexto = "OBS: lance a anotação no nome de algum oficial. Escreva o motivo ao lado";
            } else {
                placeholderTexto = "Escreva o motivo ao lado";
            }
        {% endif %}

        // Define o placeholder no campo de motivo
        motivo.placeholder = placeholderTexto;
    }

    // Chama a função ao carregar o modal e ao mudar a seleção de tipo de anotação
    $(document).ready(function() {
        atualizarObservacao();  // Chama a função ao abrir o modal

        // Atualiza o placeholder sempre que o tipo de anotação mudar
        $('#id_tipo_anotacao').on('change', atualizarObservacao);
    });

    // Submeter o formulário via AJAX
    $('#anotacaoForm').on('submit', function(event) {
        event.preventDefault();  // Prevenir o recarregamento da página

        $.ajax({
            url: "{% url 'criar_anotacao_ajax' %}?cadete_id={{ cadete_anotado.id }}",  // Enviar com o ID do cadete
            type: 'POST',
            data: $(this).serialize(),  // Serializa o formulário
            success: function(response) {
                if (response.success) {
                    $('#modalAnotacao').hide();  // Fechar o modal
                    location.reload();
                } else {
                    $('#modal-body').html(response.html_form);  // Atualizar o modal com erros, se houver
                }
            }
        });
    });
</script>

anotacao/templates/anotacao/login.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAPPA - Login</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'anotacao/img/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'anotacao/css/user_login.css' %}">
</head>
<body>
    <div class="form-container">
        <h2>Login</h2>

        <!-- Exibe mensagens de erro ou sucesso -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{% if message.tags %}{{ message.tags }}{% endif %}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <label for="id_nome_ou_numerica">Nome ou Numérica</label>
            <div class="input-container">
                {{ form.nome_ou_numerica }}
            </div>

            <label for="id_senha">Senha</label>
            <div class="input-container">
                {{ form.senha }}
                <i class="fas fa-eye" id="togglePassword"></i>
            </div>
            
            <button type="submit">Entrar</button>
        </form>
    </div>

    <script>
        // Toggle visibility for password
        const togglePassword = document.querySelector('#togglePassword');
        const senha = document.querySelector('#id_senha');

        togglePassword.addEventListener('click', function () {
            const type = senha.getAttribute('type') === 'password' ? 'text' : 'password';
            senha.setAttribute('type', type);
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    </script>
</body>
</html>